global:
  resolve_timeout: 5m

route:
  receiver: 'jenkins-webhook'
receivers:
- name: 'jenkins-webhook'
  webhook_configs:
    - url: 'http://host.docker.internal:8080/generic-webhook-trigger/invoke?token=${JENKINS_WEBHOOK_TOKEN}'
      send_resolved: true
